### ISSUE TITLE
Slackに参加できない

### ISSUE THREAD

**Issue by eggplants** [ruby-jp/ruby-jp.github.io#40]
参加リンクに遷移すると `This link is no longer active` となっています。

https://github.com/ruby-jp/ruby-jp.github.io/blob/cc3ca0e5e865527646d1ecfd1bbc7a4bb2c1c17e/_config.yml#L23

![image](https://github.com/ruby-jp/ruby-jp.github.io/assets/42153744/df334f91-2247-4c22-afc3-1e2e3b5eaabb)

**Comment by unasuke** [comment]
@eggplants 報告ありがとうございます！修正したので確認していただけますか？

**Comment by eggplants** [comment]
参加できることを確認しました。対応ありがとうございます！
